CLIQUECLIQUE_LOCALHOST = True
CLIQUECLIQUE_LOCALSIGN = False
CLIQUECLIQUE_PROFILE = False

CLIQUECLIQUE_OPTIMAL_PEER_NRS = 5

CLIQUECLIQUE_HASH_PRINT_LENGTH = 5
CLIQUECLIQUE_KEY_SIZE = 1024

CLIQUECLIQUE_I2P_SESSION_NAME = "cliqueclique"

CLIQUECLIQUE_UI_SECURITY_CONTEXTS = ["localhost:%s" % (8000 + port,) for port in xrange(0, 1)]
